

general {
    output_format = "i3bar"
    colors = true
    interval = 5
    color_good = "#879A39"
    color_degraded = "#D0A215"
    color_bad = "#D14D41"
}

order += "ipv6"
order += "wireless _first_"
order += "ethernet _first_"
order += "disk /"
order += "load"
order += "cpu_usage"
order += "cpu_temperature 0"
order += "memory"
order += "volume master"
order += "tztime local"

ipv6 {
    format_up = "Global IPv6: %ip"
    format_down = ""
}

wireless _first_ {
    format_up = "W: (%quality at %essid) %ip"
    format_down = "W: down"
}

ethernet _first_ {
    format_up = "E: %ip (%speed)"
    format_down = "E: down"
}

disk "/" {
    format = "HDD: %avail"
}

load {
    format = "CPU load: %1min"
}

cpu_usage {
    format = "CPU usage: %usage"
}

cpu_temperature 0 {
    format = "Temp: %degrees C"
    path = "/sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon3/temp1_input"

    max_threshold = 85
    format_above_threshold = "HOT: %degrees C"
}

memory {
    format = "RAM: %used"
}

tztime local {
    format = "%Y-%m-%d %H:%M"
}
